name: Update FWI

on:
  workflow_dispatch:

jobs:
  update-fwi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Run FWI
        run: python fwi_fars.py

      - name: Save FWI data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/fwi/fwi_fars.json
          git diff --cached --quiet || git commit -m "Update FWI data"
          git push
